package br.com.renovar.modelo;

// Generated 19/01/2015 15:39:32 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bairro generated by hbm2java
 */
@Entity
@Table(name = "BAIRRO", catalog = "renovar")
public class Bairro implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -290521735312751787L;
	private int baiId;
	private String baiNome;
	private String baiRegiao;
	private Set<Endereco> enderecos = new HashSet<Endereco>(0);

	public Bairro() {
	}

	public Bairro(int baiId) {
		this.baiId = baiId;
	}

	public Bairro(int baiId, String baiNome, String baiRegiao,
			Set<Endereco> enderecos) {
		this.baiId = baiId;
		this.baiNome = baiNome;
		this.baiRegiao = baiRegiao;
		this.enderecos = enderecos;
	}

	@Id
	@GeneratedValue
	@Column(name = "BAI_ID", unique = true, nullable = false)
	public int getBaiId() {
		return this.baiId;
	}

	public void setBaiId(int baiId) {
		this.baiId = baiId;
	}

	@Column(name = "BAI_NOME", length = 150)
	public String getBaiNome() {
		return this.baiNome;
	}

	public void setBaiNome(String baiNome) {
		this.baiNome = baiNome;
	}

	@Column(name = "BAI_REGIAO", length = 50)
	public String getBaiRegiao() {
		return this.baiRegiao;
	}

	public void setBaiRegiao(String baiRegiao) {
		this.baiRegiao = baiRegiao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bairro")
	public Set<Endereco> getEnderecos() {
		return this.enderecos;
	}

	public void setEnderecos(Set<Endereco> enderecos) {
		this.enderecos = enderecos;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + baiId;
		result = prime * result + ((baiNome == null) ? 0 : baiNome.hashCode());
		result = prime * result
				+ ((baiRegiao == null) ? 0 : baiRegiao.hashCode());
		result = prime * result
				+ ((enderecos == null) ? 0 : enderecos.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Bairro other = (Bairro) obj;
		if (baiId != other.baiId)
			return false;
		if (baiNome == null) {
			if (other.baiNome != null)
				return false;
		} else if (!baiNome.equals(other.baiNome))
			return false;
		if (baiRegiao == null) {
			if (other.baiRegiao != null)
				return false;
		} else if (!baiRegiao.equals(other.baiRegiao))
			return false;
		if (enderecos == null) {
			if (other.enderecos != null)
				return false;
		} else if (!enderecos.equals(other.enderecos))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Bairro [baiId=" + baiId + "]";
	}

}
