package br.com.renovar.modelo;

// Generated 28/01/2015 14:22:24 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VersaoSistema generated by hbm2java
 */
@Entity
@Table(name = "VERSAO_SISTEMA", catalog = "renovar")
public class VersaoSistema implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2196032801712790923L;
	private int verSisId;
	private String verSisNome;
	private Date verSisDataCadastro;
	private Set<Release> releases = new HashSet<Release>(0);

	public VersaoSistema() {
	}

	public VersaoSistema(int verSisId) {
		this.verSisId = verSisId;
	}

	public VersaoSistema(int verSisId, String verSisNome,
			Date verSisDataCadastro, Set<Release> releases) {
		this.verSisId = verSisId;
		this.verSisNome = verSisNome;
		this.verSisDataCadastro = verSisDataCadastro;
		this.releases = releases;
	}

	@Id
	@GeneratedValue
	@Column(name = "VER_SIS_ID", unique = true, nullable = false)
	public int getVerSisId() {
		return this.verSisId;
	}

	public void setVerSisId(int verSisId) {
		this.verSisId = verSisId;
	}

	@Column(name = "VER_SIS_NOME", length = 101)
	public String getVerSisNome() {
		return this.verSisNome;
	}

	public void setVerSisNome(String verSisNome) {
		this.verSisNome = verSisNome;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VER_SIS_DATA_CADASTRO", length = 23)
	public Date getVerSisDataCadastro() {
		return this.verSisDataCadastro;
	}

	public void setVerSisDataCadastro(Date verSisDataCadastro) {
		this.verSisDataCadastro = verSisDataCadastro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "versaoSistema")
	public Set<Release> getReleases() {
		return this.releases;
	}

	public void setReleases(Set<Release> releases) {
		this.releases = releases;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((releases == null) ? 0 : releases.hashCode());
		result = prime
				* result
				+ ((verSisDataCadastro == null) ? 0 : verSisDataCadastro
						.hashCode());
		result = prime * result + verSisId;
		result = prime * result
				+ ((verSisNome == null) ? 0 : verSisNome.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		VersaoSistema other = (VersaoSistema) obj;
		if (releases == null) {
			if (other.releases != null)
				return false;
		} else if (!releases.equals(other.releases))
			return false;
		if (verSisDataCadastro == null) {
			if (other.verSisDataCadastro != null)
				return false;
		} else if (!verSisDataCadastro.equals(other.verSisDataCadastro))
			return false;
		if (verSisId != other.verSisId)
			return false;
		if (verSisNome == null) {
			if (other.verSisNome != null)
				return false;
		} else if (!verSisNome.equals(other.verSisNome))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "VersaoSistema [verSisId=" + verSisId + "]";
	}

}
