package br.com.renovar.modelo;

// Generated 28/01/2015 14:22:24 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Atualizacao generated by hbm2java
 */
@Entity
@Table(name = "ATUALIZACAO", catalog = "renovar")
public class Atualizacao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3951668370132750923L;
	private int atuId;
	private Cliente cliente;
	private Funcionario funcionario;
	private Release release;
	private String atuTipo;
	private Date atuDataAgendadaInicio;
	private Date atuDataAgendadaFim;
	private Date atuDataAtualizada;
	private String atuDescricao;

	public Atualizacao() {
	}

	public Atualizacao(int atuId, Cliente cliente, Funcionario funcionario,
			Release release) {
		this.atuId = atuId;
		this.cliente = cliente;
		this.funcionario = funcionario;
		this.release = release;
	}

	public Atualizacao(int atuId, Cliente cliente, Funcionario funcionario,
			Release release, String atuTipo, Date atuDataAgendadaInicio,
			Date atuDataAgendadaFim, Date atuDataAtualizada, String atuDescricao) {
		this.atuId = atuId;
		this.cliente = cliente;
		this.funcionario = funcionario;
		this.release = release;
		this.atuTipo = atuTipo;
		this.atuDataAgendadaInicio = atuDataAgendadaInicio;
		this.atuDataAgendadaFim = atuDataAgendadaFim;
		this.atuDataAtualizada = atuDataAtualizada;
		this.atuDescricao = atuDescricao;
	}

	@Id
	@GeneratedValue
	@Column(name = "ATU_ID", unique = true, nullable = false)
	public int getAtuId() {
		return this.atuId;
	}

	public void setAtuId(int atuId) {
		this.atuId = atuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PES_ID", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FUN_PES_ID", nullable = false)
	public Funcionario getFuncionario() {
		return this.funcionario;
	}

	public void setFuncionario(Funcionario funcionario) {
		this.funcionario = funcionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REL_ID")
	public Release getRelease() {
		return this.release;
	}

	public void setRelease(Release release) {
		this.release = release;
	}

	@Column(name = "ATU_TIPO", length = 60)
	public String getAtuTipo() {
		return this.atuTipo;
	}

	public void setAtuTipo(String atuTipo) {
		this.atuTipo = atuTipo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ATU_DATA_AGENDADA_INICIO", length = 23)
	public Date getAtuDataAgendadaInicio() {
		return this.atuDataAgendadaInicio;
	}

	public void setAtuDataAgendadaInicio(Date atuDataAgendadaInicio) {
		this.atuDataAgendadaInicio = atuDataAgendadaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ATU_DATA_AGENDADA_FIM", length = 23)
	public Date getAtuDataAgendadaFim() {
		return this.atuDataAgendadaFim;
	}

	public void setAtuDataAgendadaFim(Date atuDataAgendadaFim) {
		this.atuDataAgendadaFim = atuDataAgendadaFim;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ATU_DATA_ATUALIZADA", length = 23)
	public Date getAtuDataAtualizada() {
		return this.atuDataAtualizada;
	}

	public void setAtuDataAtualizada(Date atuDataAtualizada) {
		this.atuDataAtualizada = atuDataAtualizada;
	}

	@Column(name = "ATU_DESCRICAO", length = 251)
	public String getAtuDescricao() {
		return this.atuDescricao;
	}

	public void setAtuDescricao(String atuDescricao) {
		this.atuDescricao = atuDescricao;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((atuDataAgendadaFim == null) ? 0 : atuDataAgendadaFim
						.hashCode());
		result = prime
				* result
				+ ((atuDataAgendadaInicio == null) ? 0 : atuDataAgendadaInicio
						.hashCode());
		result = prime
				* result
				+ ((atuDataAtualizada == null) ? 0 : atuDataAtualizada
						.hashCode());
		result = prime * result
				+ ((atuDescricao == null) ? 0 : atuDescricao.hashCode());
		result = prime * result + atuId;
		result = prime * result + ((atuTipo == null) ? 0 : atuTipo.hashCode());
		result = prime * result + ((cliente == null) ? 0 : cliente.hashCode());
		result = prime * result
				+ ((funcionario == null) ? 0 : funcionario.hashCode());
		result = prime * result + ((release == null) ? 0 : release.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Atualizacao other = (Atualizacao) obj;
		if (atuDataAgendadaFim == null) {
			if (other.atuDataAgendadaFim != null)
				return false;
		} else if (!atuDataAgendadaFim.equals(other.atuDataAgendadaFim))
			return false;
		if (atuDataAgendadaInicio == null) {
			if (other.atuDataAgendadaInicio != null)
				return false;
		} else if (!atuDataAgendadaInicio.equals(other.atuDataAgendadaInicio))
			return false;
		if (atuDataAtualizada == null) {
			if (other.atuDataAtualizada != null)
				return false;
		} else if (!atuDataAtualizada.equals(other.atuDataAtualizada))
			return false;
		if (atuDescricao == null) {
			if (other.atuDescricao != null)
				return false;
		} else if (!atuDescricao.equals(other.atuDescricao))
			return false;
		if (atuId != other.atuId)
			return false;
		if (atuTipo == null) {
			if (other.atuTipo != null)
				return false;
		} else if (!atuTipo.equals(other.atuTipo))
			return false;
		if (cliente == null) {
			if (other.cliente != null)
				return false;
		} else if (!cliente.equals(other.cliente))
			return false;
		if (funcionario == null) {
			if (other.funcionario != null)
				return false;
		} else if (!funcionario.equals(other.funcionario))
			return false;
		if (release == null) {
			if (other.release != null)
				return false;
		} else if (!release.equals(other.release))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Atualizacao [atuId=" + atuId + "]";
	}

}
