package br.com.renovar.modelo;

// Generated 02/02/2015 15:53:24 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Atendimento generated by hbm2java
 */
@Entity
@Table(name = "ATENDIMENTO", catalog = "renovar")
public class Atendimento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4559596701904384773L;
	private int ateId;
	private Cliente cliente;
	private Funcionario funcionario;
	private Date ateDataCadastro;
	private String ateDescricao;
	private String ateTipo;

	public Atendimento() {
	}

	public Atendimento(int ateId, Cliente cliente, Funcionario funcionario) {
		this.ateId = ateId;
		this.cliente = cliente;
		this.funcionario = funcionario;
	}

	public Atendimento(int ateId, Cliente cliente, Funcionario funcionario,
			Date ateDataCadastro, String ateDescricao, String ateTipo) {
		this.ateId = ateId;
		this.cliente = cliente;
		this.funcionario = funcionario;
		this.ateDataCadastro = ateDataCadastro;
		this.ateDescricao = ateDescricao;
		this.ateTipo=ateTipo;
	}

	@Id
	@GeneratedValue
	@Column(name = "ATE_ID", unique = true, nullable = false)
	public int getAteId() {
		return this.ateId;
	}

	public void setAteId(int ateId) {
		this.ateId = ateId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PES_ID", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FUN_PES_ID", nullable = false)
	public Funcionario getFuncionario() {
		return this.funcionario;
	}

	public void setFuncionario(Funcionario funcionario) {
		this.funcionario = funcionario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ATE_DATA_CADASTRO", length = 23)
	public Date getAteDataCadastro() {
		return this.ateDataCadastro;
	}

	public void setAteDataCadastro(Date ateDataCadastro) {
		this.ateDataCadastro = ateDataCadastro;
	}

	@Column(name = "ATE_DESCRICAO", length = 251)
	public String getAteDescricao() {
		return this.ateDescricao;
	}

	public void setAteDescricao(String ateDescricao) {
		this.ateDescricao = ateDescricao;
	}
	@Column(name = "ATE_TIPO", length = 90)
	public String getAteTipo() {
		return ateTipo;
	}

	public void setAteTipo(String ateTipo) {
		this.ateTipo = ateTipo;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((ateDataCadastro == null) ? 0 : ateDataCadastro.hashCode());
		result = prime * result
				+ ((ateDescricao == null) ? 0 : ateDescricao.hashCode());
		result = prime * result + ateId;
		result = prime * result + ((cliente == null) ? 0 : cliente.hashCode());
		result = prime * result
				+ ((funcionario == null) ? 0 : funcionario.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Atendimento other = (Atendimento) obj;
		if (ateDataCadastro == null) {
			if (other.ateDataCadastro != null)
				return false;
		} else if (!ateDataCadastro.equals(other.ateDataCadastro))
			return false;
		if (ateDescricao == null) {
			if (other.ateDescricao != null)
				return false;
		} else if (!ateDescricao.equals(other.ateDescricao))
			return false;
		if (ateId != other.ateId)
			return false;
		if (cliente == null) {
			if (other.cliente != null)
				return false;
		} else if (!cliente.equals(other.cliente))
			return false;
		if (funcionario == null) {
			if (other.funcionario != null)
				return false;
		} else if (!funcionario.equals(other.funcionario))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Atendimento [ateId=" + ateId + "]";
	}

}
