package br.com.renovar.modelo;

// Generated 16/01/2015 15:33:10 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Historico generated by hbm2java
 */
@Entity
@Table(name = "HISTORICO", catalog = "renovar")
public class Historico implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9215846417877738459L;
	private int hisId;
	private Cliente cliente;
	private String hisSituacao;
	private Date hisDataContato;
	private String hisChamado;

	public Historico() {
	}

	public Historico(int hisId, Cliente cliente) {
		this.hisId = hisId;
		this.cliente = cliente;
	}

	public Historico(int hisId, Cliente cliente, String hisSituacao,
			Date hisDataContato, String hisChamado) {
		this.hisId = hisId;
		this.cliente = cliente;
		this.hisSituacao = hisSituacao;
		this.hisDataContato = hisDataContato;
		this.hisChamado = hisChamado;
	}

	@Id
	@GeneratedValue
	@Column(name = "HIS_ID", unique = true, nullable = false)
	public int getHisId() {
		return this.hisId;
	}

	public void setHisId(int hisId) {
		this.hisId = hisId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PES_ID", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "HIS_SITUACAO", length = 200)
	public String getHisSituacao() {
		return this.hisSituacao;
	}

	public void setHisSituacao(String hisSituacao) {
		this.hisSituacao = hisSituacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HIS_DATA_CONTATO", length = 23)
	public Date getHisDataContato() {
		return this.hisDataContato;
	}

	public void setHisDataContato(Date hisDataContato) {
		this.hisDataContato = hisDataContato;
	}

	@Column(name = "HIS_CHAMADO", length = 30)
	public String getHisChamado() {
		return this.hisChamado;
	}

	public void setHisChamado(String hisChamado) {
		this.hisChamado = hisChamado;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cliente == null) ? 0 : cliente.hashCode());
		result = prime * result
				+ ((hisChamado == null) ? 0 : hisChamado.hashCode());
		result = prime * result
				+ ((hisDataContato == null) ? 0 : hisDataContato.hashCode());
		result = prime * result + hisId;
		result = prime * result
				+ ((hisSituacao == null) ? 0 : hisSituacao.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Historico other = (Historico) obj;
		if (cliente == null) {
			if (other.cliente != null)
				return false;
		} else if (!cliente.equals(other.cliente))
			return false;
		if (hisChamado == null) {
			if (other.hisChamado != null)
				return false;
		} else if (!hisChamado.equals(other.hisChamado))
			return false;
		if (hisDataContato == null) {
			if (other.hisDataContato != null)
				return false;
		} else if (!hisDataContato.equals(other.hisDataContato))
			return false;
		if (hisId != other.hisId)
			return false;
		if (hisSituacao == null) {
			if (other.hisSituacao != null)
				return false;
		} else if (!hisSituacao.equals(other.hisSituacao))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Historico [hisId=" + hisId + "]";
	}

}
