package br.com.renovar.modelo;

// Generated 28/01/2015 14:22:24 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Release generated by hbm2java
 */
@Entity
@Table(name = "RELEASE", catalog = "renovar")
public class Release implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 401476778329782919L;
	private int relId;
	private VersaoSistema versaoSistema;
	private String relNome;
	private Date relDataCadastro;
	private Set<Atualizacao> atualizacaos = new HashSet<Atualizacao>(0);

	public Release() {
	}

	public Release(int relId, VersaoSistema versaoSistema) {
		this.relId = relId;
		this.versaoSistema = versaoSistema;
	}

	public Release(int relId, VersaoSistema versaoSistema, String relNome,
			Date relDataCadastro, Set<Atualizacao> atualizacaos) {
		this.relId = relId;
		this.versaoSistema = versaoSistema;
		this.relNome = relNome;
		this.relDataCadastro = relDataCadastro;
		this.atualizacaos = atualizacaos;
	}

	@Id
	@GeneratedValue
	@Column(name = "REL_ID", unique = true, nullable = false)
	public int getRelId() {
		return this.relId;
	}

	public void setRelId(int relId) {
		this.relId = relId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VER_SIS_ID", nullable = false)
	public VersaoSistema getVersaoSistema() {
		return this.versaoSistema;
	}

	public void setVersaoSistema(VersaoSistema versaoSistema) {
		this.versaoSistema = versaoSistema;
	}

	@Column(name = "REL_NOME", length = 90)
	public String getRelNome() {
		return this.relNome;
	}

	public void setRelNome(String relNome) {
		this.relNome = relNome;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REL_DATA_CADASTRO", length = 23)
	public Date getRelDataCadastro() {
		return this.relDataCadastro;
	}

	public void setRelDataCadastro(Date relDataCadastro) {
		this.relDataCadastro = relDataCadastro;
	}
	@Transient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "release")
	public Set<Atualizacao> getAtualizacaos() {
		return this.atualizacaos;
	}

	public void setAtualizacaos(Set<Atualizacao> atualizacaos) {
		this.atualizacaos = atualizacaos;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((atualizacaos == null) ? 0 : atualizacaos.hashCode());
		result = prime * result
				+ ((relDataCadastro == null) ? 0 : relDataCadastro.hashCode());
		result = prime * result + relId;
		result = prime * result + ((relNome == null) ? 0 : relNome.hashCode());
		result = prime * result
				+ ((versaoSistema == null) ? 0 : versaoSistema.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Release other = (Release) obj;
		if (atualizacaos == null) {
			if (other.atualizacaos != null)
				return false;
		} else if (!atualizacaos.equals(other.atualizacaos))
			return false;
		if (relDataCadastro == null) {
			if (other.relDataCadastro != null)
				return false;
		} else if (!relDataCadastro.equals(other.relDataCadastro))
			return false;
		if (relId != other.relId)
			return false;
		if (relNome == null) {
			if (other.relNome != null)
				return false;
		} else if (!relNome.equals(other.relNome))
			return false;
		if (versaoSistema == null) {
			if (other.versaoSistema != null)
				return false;
		} else if (!versaoSistema.equals(other.versaoSistema))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Release [relId=" + relId + ", versaoSistema=" + versaoSistema
				+ ", relNome=" + relNome + ", relDataCadastro="
				+ relDataCadastro + ", atualizacaos=" + atualizacaos + "]";
	}



}
